server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
      - id: client-ms
        uri: lb://client-ms   
        predicates:
        - Path=/client-ms/**
      - id: employee-ms
        uri: lb://employee-ms   
        predicates:
        - Path=/employee-ms/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/** 
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs 
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka