server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
      - id: /api/client
        uri: lb://client-ms   
        predicates:
        - Path=/api/client/**
      - id: /api/employee
        uri: lb://employee-ms   
        predicates:
        - Path=/api/employee/**  
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka